### ISSUE TITLE
Tutorial Site Down

### ISSUE THREAD

**Issue by AllieDeford** [hds-lab/d3tutorial#1]
I just attempted to access the tutorial site via the given link (http://scclab.github.io/d3tutorial), but I keep receiving a 404 error. Other Github Pages sites are loading normally.

**Comment by michaelbrooks** [comment]
I just renamed the lab's GitHub account this afternoon, which broke this site since it is hosted on GitHub. The new link is http://hds-lab.github.io/d3tutorial and the old one should now automatically redirect. Thanks for pointing this out!
